name: Update Hafzan Composite Index Data

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the script every day at midnight UTC
  push:
    branches:
      - main  # Trigger when code is pushed to the 'main' branch

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script to generate data
        run: |
          python generate_data.py

      - name: Commit and push updated data
        run: |
          git add data.json
          git commit -m "Update Hafzan Composite Index data"
          git push
