name: Update Hafzan Index

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight
  push:
    branches:
      - main  # Trigger the action when pushing to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Generate Chart
      run: |
        python generate_chart.py  # Run the script to generate index.html

    - name: Deploy to gh-pages
      run: |
        git config --global user.name "your-username"
        git config --global user.email "your-email@example.com"
        git checkout -B gh-pages  # Switch to gh-pages branch
        git add index.html  # Add the updated index.html file
        git commit -m "Update Hafzan Composite Index"
        git push -f origin gh-pages  # Force push to gh-pages
