name: Update Hafzan Index

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - gh-pages  # Only trigger on changes to gh-pages branch

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the Python script
      run: |
        python generate_chart.py

    - name: Commit and push data.json
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        git add data.json
        git commit -m "Update data.json with the latest stock data"
        git push
